export class CostProject {
  /**
   * Database Column Remarks:
   *   主键id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_project.id
   *
   * @mbg.generated Mon Jun 11 21:13:51 CST 2018
   */
   id: number;

  /**
   * Database Column Remarks:
   *   名称
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_project.name
   *
   * @mbg.generated Mon Jun 11 21:13:51 CST 2018
   */
   name: string;

  /**
   * Database Column Remarks:
   *   编码
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_project.code
   *
   * @mbg.generated Mon Jun 11 21:13:51 CST 2018
   */
   code: string;


  constructor(id?: number, name?: string, code?: string) {
    this.id = id;
    this.name = name;
    this.code = code;
  }
}
