import { Device } from './device';
import { CostProject } from './cost-project';
import { DevicePriceRule } from './device-price-rule';
import { PayChannel } from './pay-channel';
import { DeductionType } from './deduction-type';
import {User} from './user';

export class CostPrice {

  /**
   * Database Column Remarks:
   *   主键id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  id: number;

  /**
   * Database Column Remarks:
   *   机器外键
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.device_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  deviceId: number;

  device: Device;

  /**
   * Database Column Remarks:
   *   消费时间
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.cost_time
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  costTime: Date;

  /**
   * Database Column Remarks:
   *   消费明目外键id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.cost_project_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  costProjectId: number;

  costProject: CostProject;

  /**
   * Database Column Remarks:
   *   扣费类型外键id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.deduction_type_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  deductionTypeId: number;

  deductionType: DeductionType;

  /**
   * Database Column Remarks:
   *   支付渠道
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.pay_channel_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  payChannelId: number;

  payChannel: PayChannel;

  /**
   * Database Column Remarks:
   *   价格模版外键id(消费科目)
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.device_price_type_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  devicePriceTypeId: number;

  devicePriceRule: DevicePriceRule;

  /**
   * Database Column Remarks:
   *   系统流水号
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.system_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  systemId: string;

  /**
   * Database Column Remarks:
   *   微信交易流水号
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.wechat_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  wechatId: string;

  /**
   * Database Column Remarks:
   *   用户表外键
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.user_id
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  userId: number;

  user: User;

  /**
   * Database Column Remarks:
   *   消费金额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cost_price.amount
   *
   * @mbg.generated Mon Jun 11 21:51:37 CST 2018
   */
  amount: number;
}
