import {s, st} from '@angular/core/src/render3';
import { DeviceType } from './device-type';

export class Device {
  /**
   * Database Column Remarks:
   *   设备id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.id
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   id: number;

  /**
   * Database Column Remarks:
   *   机器码
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.code
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   code: string;

  /**
   * Database Column Remarks:
   *   设备型号
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.machine_type
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
  equipmentModel: string;

  /**
   * Database Column Remarks:
   *   设备名称
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.name
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   name: string;

  /**
   * Database Column Remarks:
   *   品牌
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.brand
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   brand: string;

  /**
   * Database Column Remarks:
   *   场地名称
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.location_name
   *
   * @mbg.generated Wed Jun 06 23:56:36 CST 2018
   */
   locationName: string;

  /**
   * Database Column Remarks:
   *   联系电话
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.phone
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   phone: string;

  /**
   * Database Column Remarks:
   *   机器摆放地址
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.location
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   location: string;

  /**
   * Database Column Remarks:
   *   启用状态
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.is_enable
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   isEnable: boolean;

  /**
   * Database Column Remarks:
   *   七天营业额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.weekday
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   weekday: number;

  /**
   * Database Column Remarks:
   *   营业额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.total
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
  total: number;

  /**
   * Database Column Remarks:
   *   30天营业额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.month
   *
   * @mbg.generated Wed Jun 06 23:56:36 CST 2018
   */
   month: number;

  /**
   * Database Column Remarks:
   *   是否在线
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.is_online
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   isOnline: boolean;

  /**
   * Database Column Remarks:
   *   运行状态
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.status
   *
   * @mbg.generated Wed Jun 06 22:40:27 CST 2018
   */
   status: number;

  /**
   * Database Column Remarks:
   *   设备类型对应device_type中的id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device.device_type
   *
   * @mbg.generated Fri Jun 08 14:57:10 CST 2018
   */
   deviceTypeId: number;

   deviceType: DeviceType;

   constructor(id?: number, code?: string, equipmentModel?: string,
               name?: string, brand?: string, locationName?: string,
               phone?: string, location?: string, isEnable?: boolean,
               weekday?: number, total?: number, month?: number,
               isOnline?: boolean, status?: number, deviceType?: number) {
    this.id = id;
    this.code = code;
    this.equipmentModel = equipmentModel;
    this.name = name;
    this.brand = brand;
    this.locationName = locationName;
    this.phone = phone;
    this.location = location;
    this.isEnable = isEnable;
    this.weekday = weekday;
    this.total = total;
    this.month = month;
    this.isOnline = isOnline;
    this.status = status;
    this.deviceTypeId = deviceType;
  }
}
