export class DeviceType {
  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_type.id
   *
   * @mbg.generated Fri Jun 08 14:51:49 CST 2018
   */
   id: number;

  /**
   * Database Column Remarks:
   *   类型名称
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_type.name
   *
   * @mbg.generated Fri Jun 08 14:51:49 CST 2018
   */
   name: string;

  /**
   * Database Column Remarks:
   *   类型编码
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_type.code
   *
   * @mbg.generated Fri Jun 08 14:51:49 CST 2018
   */
   code: string;


  constructor(id?: number, name?: string, code?: string) {
    this.id = id;
    this.name = name;
    this.code = code;
  }
}
