export class DevicePriceRule {
  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_price_rule.id
   *
   * @mbg.generated Fri Jun 08 21:16:24 CST 2018
   */
  id: number;

  /**
   * Database Column Remarks:
   *   设备类型（device_type表）外键id
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_price_rule.device_type_id
   *
   * @mbg.generated Fri Jun 08 21:16:24 CST 2018
   */
  deviceTypeId: number;

  /**
   * Database Column Remarks:
   *   显示名称
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_price_rule.name
   *
   * @mbg.generated Fri Jun 08 21:16:24 CST 2018
   */
  name: string;

  /**
   * Database Column Remarks:
   *   信号标识
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_price_rule.signal_identification
   *
   * @mbg.generated Fri Jun 08 21:16:24 CST 2018
   */
  signalIdentification: string;

  /**
   * Database Column Remarks:
   *   消费金额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_price_rule.cost
   *
   * @mbg.generated Fri Jun 08 21:16:24 CST 2018
   */
  cost: number;

  /**
   * Database Column Remarks:
   *   描述
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column device_price_rule.description
   *
   * @mbg.generated Fri Jun 08 21:16:24 CST 2018
   */
  description: string;


  constructor(id?: number,
              deviceTypeId?: number,
              name?: string,
              signalIdentification?: string,
              cost?: number,
              description?: string) {
    this.id = id;
    this.deviceTypeId = deviceTypeId;
    this.name = name;
    this.signalIdentification = signalIdentification;
    this.cost = cost;
    this.description = description;
  }
}
