export class SettlementReport {

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.id
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    id: number;

  /**
   * Database Column Remarks:
   *   客户名称
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.custom_name
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    customName: string;

  /**
   * Database Column Remarks:
   *   申请提现日期
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.apply_cash_datei
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    applyCashDatei: Date;

  /**
   * Database Column Remarks:
   *   结算日期
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.balance_date
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    balanceDate: Date;

  /**
   * Database Column Remarks:
   *   系统订单结算编号
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.sys_order_id
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    sysOrderId: string;

  /**
   * Database Column Remarks:
   *   微信结算订单号
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.weixin_order_id
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    weixinOrderId: string;

  /**
   * Database Column Remarks:
   *   结算订单数(单)
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.order_num
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    orderNum: number;

  /**
   * Database Column Remarks:
   *   结算金额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.settlement_amount
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    settlementAmount: number;

  /**
   * Database Column Remarks:
   *   结算费率
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.settlement_ratio
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    settlementRatio: number;

  /**
   * Database Column Remarks:
   *   最终结算金额
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column settlement_report.settlement_total
   *
   * @mbg.generated Tue Jun 12 21:10:56 CST 2018
   */
    settlementTotal: number;


  constructor(id: number,
              customName: string,
              applyCashDatei: Date,
              balanceDate: Date,
              sysOrderId: string,
              weixinOrderId: string,
              orderNum: number,
              settlementAmount: number,
              settlementRatio: number,
              settlementTotal: number) {
    this.id = id;
    this.customName = customName;
    this.applyCashDatei = applyCashDatei;
    this.balanceDate = balanceDate;
    this.sysOrderId = sysOrderId;
    this.weixinOrderId = weixinOrderId;
    this.orderNum = orderNum;
    this.settlementAmount = settlementAmount;
    this.settlementRatio = settlementRatio;
    this.settlementTotal = settlementTotal;
  }
}
